
---
-- @type EntityController
EntityController = {
    Pointer = 0,
    MoveX = 0,
    MoveY = 0,
    CamRotSpeedH = 0,
    CamRotSpeedV = 0,
    CamRotH = 0,
    CamRotV = 0,
    R1Held_Sometimes = false,
    L2OrR1Held_Sometimes = false,
    RMouseHeld = false,
    R1Held = false,
    XHeld = false,
    L1Held = false,
    L2OrTabHeld = false,
    L1Held2 = false,
    R1HeldOrCircleTapped = false,
    RMouseOrR2Held = false,
    R1OrLMouseHeld = false,
    L2Held = false,
    CircleTapped = false,
    XHeld2 = false,
    L1Held3 = false,
    L2Held2 = false,
    L1Held4 = false,
    SecondsR1Held = 0,
    SecondsGuarding = 0,
    SecondsR2Held = 0,
    SecondsR1Held2 = 0,
    SecondsL1Held = 0,
    SecondsGuarding2 = 0,
    AnimationID = 0,
    AIControllerPtr = 0,
    AIController = EntityAIController
}