'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("DaS_BRush.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1|1
        '''1000|Shaved (1000)
        '''1100|Receding
        '''1200|Short
        '''1300|Swept Back
        '''1400|Ponytail
        '''1500|Wild
        '''1600|Parted Center
        '''1700|Semi-Long
        '''1800|Curly
        '''1900|Bobbed
        '''2000|Male 11
        '''2100|Male 12
        '''2200|Male 13
        '''2300|Male 14
        '''2400|Male 15
        '''2500|Male 16
        '''2600|Male 17
        '''2700|Male 18
        '''2800|Male 19
        '''2900|Male 20
        '''3000|Shaved (3000)
        '''3100|Very Short
        '''3200|Wave
        '''3300|Straight A
        '''3400|Straight B
        '''3500|Ponytail A
        '''3600|Ponytail B
        '''3700|Pigtails
        '''3800|Bun
        '''3900|Braided
        '''4000|Female 11
        '''4100|Female 12
        '''4200|Female 13
        '''4300|Female 1 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Armor() As String
            Get
                Return ResourceManager.GetString("Armor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to -1|Nothing
        '''1002900|Depths (Entrance)
        '''1002950|Depths (Gaping Dragon&apos;s Room)
        '''1002960|Depths (Bonfire)
        '''1012960|Undead Burg (Pre-Dragon Scare)
        '''1012961|Undead Parish (Sunlight Altar Bonfire)
        '''1012962|Undead Burg (Bonfire)
        '''1012964|Undead Parish (Bonfire)
        '''1012965|Undead Parish (Near Boar)
        '''1012966|Undead Parish (Near Cell)
        '''1020980|Firelink Shrine (Bonfire, repeat)
        '''1022960|Firelink Shrine (Bonfire)
        '''1102960|Painted World of Ariamis (Bonfire)
        '''1102961|Painted World of Ariamis (Entrance)
        '''1202961|Darkroot Ga [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Bonfires() As String
            Get
                Return ResourceManager.GetString("Bonfires", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to -1|Nothing
        '''1602950|Abyss (Bonfire)
        '''1512962|Anor Londo (Gwyndolin Bonfire)
        '''1512950|Anor Londo (Gwynevere Bonfire)
        '''1512961|Anor Londo (Interior Bonfire)
        '''1512960|Anor Londo (Lady of the Darkling Bonfire)
        '''1322961|Ash Lake (Bonfire #1)
        '''1322960|Ash Lake (Bonfire #2)
        '''1402962|Blighttown (Bridge Bonfire)
        '''1402963|Blighttown (Entrance)
        '''1402961|Blighttown (Swamp Bonfire)
        '''1212950|Chasm of the Abyss (Manus)
        '''1702950|Crystal Cave (Seath)
        '''1602961|Darkroot Basin (Bonfire)
        '''1202961|Darkroot Garden (Bonfire)
        '''1412 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Bonfires1() As String
            Get
                Return ResourceManager.GetString("Bonfires1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 14030544|ActionEnd
        '''14023712|AddActionCount
        '''14017664|AddBlockClearBonus
        '''14019616|AddClearCount
        '''14027056|AddCorpseEvent
        '''14024912|AddCurrentVowRankPoint
        '''14042560|AddCustomRoutePoint
        '''14016032|AddDeathCount
        '''14028016|AddEventParts_Ignore
        '''14035040|AddEventSimpleTalk
        '''14034976|AddEventSimpleTalkTimer
        '''14034832|AddFieldInsFilter
        '''14033584|AddGeneEvent
        '''14015312|AddHelpWhiteGhost
        '''14044496|AddHitMaskByBit
        '''14042912|AddInfomationBuffer
        '''14042928|AddInfomationBufferTag
        '''14033776|AddInfomationList
        '''14042864|Add [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property FuncLocs() As String
            Get
                Return ResourceManager.GetString("FuncLocs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 100|White Sign Soapstone
        '''101|Red Sign Soapstone
        '''102|Red Eye Orb
        '''103|Black Separation Crystal
        '''106|Orange Guidance Soapstone
        '''108|Book of the Guilty
        '''109|Eye of Death
        '''111|Cracked Red Eye Orb
        '''112|Servant Roster
        '''113|Blue Eye Orb
        '''114|Dragon Eye
        '''115|Black Eye Orb (115)
        '''116|Black Eye Orb (116)
        '''117|Darksign
        '''118|Purple Coward&apos;s Crystal
        '''200|Estus Flask (200)
        '''201|Estus Flask (201)
        '''202|Estus Flask+1 (202)
        '''203|Estus Flask+1 (203)
        '''204|Estus Flask+2 (204)
        '''205|Estus Flask+2 (205)
        '''206|Estus Flask+3 (206)        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Goods() As String
            Get
                Return ResourceManager.GetString("Goods", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 100|Havel&apos;s Ring
        '''101|Red Tearstone Ring
        '''102|Darkmoon Blade Covenant Ring
        '''103|Cat Covenant Ring
        '''104|Cloranthy Ring
        '''105|Flame Stoneplate Ring
        '''106|Thunder Stoneplate Ring
        '''107|Spell Stoneplate Ring
        '''108|Speckled Stoneplate Ring
        '''109|Bloodbite Ring
        '''110|Poisonbite Ring
        '''111|Tiny Being&apos;s Ring
        '''113|Cursebite Ring
        '''114|White Seance Ring
        '''115|Bellowing Dragoncrest Ring
        '''116|Dusk Crown Ring
        '''117|Hornet Ring
        '''119|Hawk Ring
        '''120|Ring of Steel Protection
        '''121|Covetous Gold Serpent Ring
        '''122|Covetous Silver Serpen [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Rings() As String
            Get
                Return ResourceManager.GetString("Rings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 454001|454001
        '''454002|454002
        '''454003|454003
        '''454004|454004
        '''454005|454005
        '''498000|498000
        '''499000|499000
        '''599000|599000
        '''699000|699000
        '''798000|798000
        '''799000|799000
        '''898000|898000
        '''899000|899000
        '''999000|999000
        '''1398000|1398000
        '''1399000|1399000
        '''1699000|1699000
        '''9004000|9004000
        '''9004100|9004100
        '''9004200|9004200
        '''9004400|9004400
        '''9004600|9004600
        '''9004800|9004800
        '''9005000|9005000
        '''9005100|9005100
        '''9005200|9005200
        '''9005400|9005400
        '''9005600|9005600
        '''9005800|9005800
        '''9006000|9006000
        '''9006100|9006100
        '''9006200|90062 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Weapons() As String
            Get
                Return ResourceManager.GetString("Weapons", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
